# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.27.1
    hooks:
    -   id: markdownlint
        args: [--fix]
        exclude: "docs/"
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
        exclude: "docs/"
    -   id: end-of-file-fixer
        exclude: "docs/"
    -   id: check-yaml
        exclude: "docs/"
    -   id: check-added-large-files
        args: ["--maxkb=80000"]
-   repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
    - id: isort
      types: [python]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
    -   id: mypy
-   repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
    -   id: black
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.1.3
    hooks:
    -   id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
    -   id: parsable-R
    -   id: no-browser-statement
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 0.9.0
    hooks:
    -   id: nbqa-isort
        args: [--nbqa-mutate]
    -   id: nbqa-black
        args: [--nbqa-mutate]
    -   id: nbqa-pyupgrade
        args: [--nbqa-mutate]
    -   id: nbqa-mypy
        args: [--nbqa-mutate]
        types: [jupyter]
