---
title: "Analyzing the results of \"Registered Replication Report: Strack, Martin, and Stepper (1988)\""
description: |
  My own visualization and statistical analysis of the data from a replication study of this famous phsycology paper.
author:
  - first_name: "Joshua"
    last_name: "Cook"
    url: https://joshuacook.netlify.app
    orcid_id: 0000-0001-9815-6879
date: "May 23, 2021"
output:
  distill::distill_article:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = "#>", dpi = 400)

library(mustashe)
library(nakedpipe)
library(magrittr)
library(tidyverse)

theme_set(
  theme_minimal() +
    theme(
      strip.text = element_text(face = "bold"),
      plot.title = element_text(hjust = 0.5)
    )
)
```

## Data preparation

```{r, echo=TRUE}
subjects_to_remove <- c("63", "39")

# CLean the initial data columns.
data <- read_csv("data/Wagenmakers-data_modified.csv") %.% {
  janitor::clean_names()
  mutate(
    subject_number = factor(subject_number),
    participant_id = factor(participant_id),
    across(starts_with("cartoon") & ends_with("correct"), as.logical),
    aware_of_goal = as.logical(aware_of_goal),
    comprehension_of_cartoons = as.logical(comprehension_of_cartoons),
    student = as.logical(student),
    gender = case_when(
      gender == 1 ~ "M",
      gender == 0 ~ "F",
      TRUE ~ NA_character_
    )
  )
  filter(!subject_number %in% subjects_to_remove)
}

# Pivot the data into a long format.
data <- data %.% {
  select(-contains("task"), -guess_of_purpose)
  pivot_longer(cols = c(contains("cartoon"), -comprehension_of_cartoons))
  mutate(name = str_remove(name, "^cartoon_"))
  separate(name, into = c("cartoon_number", "variable"), sep = "_")
  pivot_wider(names_from = variable, values_from = value)
  mutate(
    correct = as.logical(correct),
    cartoon_number = glue::glue("Cartoon {cartoon_number}"),
    condition = ifelse(condition, "frown", "smile")
  )
}
```

```{r}
naniar::miss_var_summary(data) %>%
  filter(n_miss > 0) %>%
  rename(
    `num. missing` = n_miss,
    `percent missing` = pct_miss
  ) %>%
  kableExtra::kbl() %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "responsive"))
```

Exclude subjects who:

- were aware of the research goal,
- did not understand the cartoons

```{r, echo=TRUE}
excluded_subjects <- data %.% {
  filter(aware_of_goal | !comprehension_of_cartoons | total_correct <= 2)
  pull(subject_number)
  unlist()
  unique()
}

data <- data %>%
  mutate(excluded_data = subject_number %in% excluded_subjects)
```

`r length(excluded_subjects)` subjects were excluded from the data.


## Data visualization

```{r}
data %>%
  filter(!is.na(rating)) %>%
  ggplot(aes(x = condition, y = rating)) +
  facet_wrap(~cartoon_number) +
  geom_boxplot(
    aes(color = condition, fill = condition),
    alpha = 0.2,
    outlier.shape = NA
  ) +
  scale_color_brewer(type = "qual", palette = "Set1") +
  scale_fill_brewer(type = "qual", palette = "Set1") +
  labs(x = NULL, y = "fraction")
```

```{r}
data %>%
  filter(!is.na(rating)) %>%
  ggplot(aes(x = condition, y = rating)) +
  facet_wrap(~cartoon_number) +
  geom_point(
    aes(color = gender),
    size = 1,
    alpha = 0.5,
    position = position_jitterdodge(0.2, 0.25, seed = 0)
  ) +
  geom_boxplot(
    aes(color = gender, fill = gender),
    alpha = 0.2,
    outlier.shape = NA
  ) +
  scale_color_brewer(type = "qual", palette = "Set2") +
  scale_fill_brewer(type = "qual", palette = "Set2") +
  labs(x = NULL, y = "fraction")
```


```{r}
rating_counts <- data %.% {
  filter(!is.na(rating) & !excluded_data)
  count(condition, rating, cartoon_number)
  tidyr::complete(condition, rating, cartoon_number, fill = list(n = 0))
  mutate(cartoon_number = glue::glue("cartoon {cartoon_number}"))
  group_by(condition, cartoon_number)
  mutate(frac = n / sum(n))
  ungroup()
}


rating_counts %>%
  ggplot(aes(x = factor(rating), y = n)) +
  facet_grid(condition ~ cartoon_number) +
  geom_col(aes(fill = condition), position = "dodge") +
  scale_fill_brewer(type = "qual", palette = "Set1") +
  scale_y_continuous(expand = expansion(c(0, 0.02))) +
  labs(
    x = "cartoon rating",
    y = "count",
    fill = "condition"
  )
```

```{r}
rating_counts %>%
  ggplot(aes(x = factor(rating), y = frac)) +
  facet_wrap(~cartoon_number) +
  geom_line(
    aes(group = condition, color = condition),
    alpha = 0.5,
    size = 1
  ) +
  geom_point(aes(color = condition), size = 2, alpha = 0.8) +
  scale_color_brewer(type = "qual", palette = "Set1") +
  scale_y_continuous(expand = expansion(c(0.01, 0.02))) +
  labs(
    x = "cartoon rating",
    y = "fraction",
    color = "condition"
  )
```

```{r}
rating_counts %.%
  {
    select(-n)
    pivot_wider(names_from = condition, values_from = frac)
    mutate(difference = smile - frown)
  } %>%
  ggplot(aes(x = factor(rating), y = difference)) +
  facet_wrap(~cartoon_number) +
  geom_hline(yintercept = 0) +
  geom_linerange(
    aes(ymax = difference),
    ymin = 0,
    alpha = 0.2,
    size = 1
  ) +
  geom_line(
    group = 1,
    alpha = 0.2,
    size = 1.3,
    color = "black"
  ) +
  geom_point(aes(color = difference), size = 2.5) +
  scale_color_gradient2(
    low = "blue",
    high = "red",
    mid = "grey70",
    guide = FALSE
  ) +
  labs(
    x = "cartoon rating",
    y = "diff. fraction (smile - frown)"
  )
```

```{r, message=FALSE, warning=FALSE}
rating_summaries <- data %>%
  filter(!is.na(rating)) %>%
  group_by(
    participant_id,
    condition,
    gender,
    comprehension_of_cartoons,
    correct,
    excluded_data
  ) %>%
  summarize(
    avg_rating = mean(rating),
    avg_age = mean(age)
  ) %>%
  ungroup()
```

```{r}
rating_summaries %>%
  ggplot(aes(x = avg_age, y = avg_rating)) +
  geom_jitter(
    aes(color = condition, shape = excluded_data),
    width = 0.5,
    height = 0.1,
    size = 1.5,
    alpha = 0.7
  ) +
  scale_color_brewer(type = "qual", palette = "Set1") +
  scale_shape_manual(values = c(19, 4), labels = c("included", "excluded")) +
  labs(
    x = "avgerage age",
    y = "average cartoon rating",
    color = "condition",
    shape = NULL
  )
```

## Analysis

```{r}
library(bayestestR)
library(see)
library(tidybayes)
library(bayesplot)
library(rstanarm)
```

```{r}
model_data <- data %.% {
  filter(!excluded_data)
  filter(correct)
  mutate(cartoon_number = factor(cartoon_number))
}
```


```{r}
stash("m1", depends_on = "model_data", {
  m1 <- stan_lm(
    rating ~ 1 + cartoon_number,
    data = model_data,
    prior = R2(0.5),
    prior_intercept = normal(0, 5),
    seed = 0,
    cores = 2
  )
  m1$loo <- rstanarm::loo(m1, cores = 2)
  m1
})
```

```{r}
plotdata <- model_data %.% {
  select(cartoon_number, rating)
  mutate(pred = predict(m1))
  pivot_longer(c(rating, pred))
}

ggplot(plotdata, aes(x = value)) +
  facet_wrap(~cartoon_number) +
  geom_density(aes(color = name, fill = name), alpha = 0.2, size = 1)
```

```{r}
stash("m2", depends_on = "model_data", {
  m2 <- stan_lmer(
    rating ~ (1 | subject_number) + (1 | cartoon_number) + condition,
    data = model_data,
    seed = 0,
    cores = 2
  )
  m2$loo <- rstanarm::loo(m2, cores = 2, k_threshold = 0.7)
  m2
})
```

```{r message=FALSE, warning=FALSE}
as_tibble(
  bayestestR::describe_posterior(
    m2,
    effects = "all",
    parameters = "smile|cartoon"
  )
) %>%
  select(-Effects)
```

```{r}
m2_post_main <- as.data.frame(m2) %>%
  as_tibble() %>%
  select(!contains("subject_number"))

m2_post_main %>%
  select(-`Sigma[cartoon_number:(Intercept),(Intercept)]`) %>%
  mutate(sample_id = row_number()) %>%
  pivot_longer(-sample_id) %>%
  mutate(
    name = str_remove(name, "^b\\[\\(Intercept\\) cartoon_number\\:"),
    name = str_remove(name, "\\]$"),
    name = str_remove(name, "^condition"),
    name = str_replace_all(name, "_", " "),
    name = fct_rev(fct_inorder(name))
  ) %>%
  ggplot(aes(value, name)) +
  geom_vline(xintercept = 0, linetype = 2) +
  ggridges::geom_density_ridges(alpha = 0.4, bandwidth = 0.05) +
  scale_x_continuous(expand = c(0, 0)) +
  labs(
    x = "posterior",
    y = NULL,
    title = "Posterior distribtions for model 2"
  )
```

```{r}
as_tibble(
  bayestestR::describe_posterior(
    m2,
    effects = "random",
    paramters = "subject_number"
  )
) %>%
  filter(Effects == "random") %>%
  arrange(Median) %>%
  mutate(Parameter = fct_inorder(Parameter)) %>%
  ggplot(aes(Parameter)) +
  geom_hline(yintercept = 0, linetype = 2, alpha = 0.5) +
  geom_linerange(aes(ymin = CI_low, ymax = CI_high), alpha = 0.2) +
  geom_point(aes(y = Median, color = Median), alpha = 0.7, size = 1) +
  scale_color_gradient2(mid = "grey80") +
  theme(
    axis.text.x = element_blank(),
    panel.grid.major.x = element_blank()
  ) +
  labs(
    x = "test subjects",
    y = "posterior",
    title = "Distribution of subject varying intercepts"
  )
```

```{r}
stash("m3", depends_on = "model_data", {
  m3 <- stan_lmer(
    rating ~ (1 | subject_number) + (1 | cartoon_number) + condition + gender + student + age,
    data = model_data,
    seed = 0,
    cores = 2
  )
  m3$loo <- rstanarm::loo(m3, cores = 2)
  m3
})
```

```{r}
stash("model_comparison", depends_on = c("m1", "m2", "m3", "model_data"), {
  model_comparison <- loo_compare(m1, m2, m3)
})
model_comparison
```

```{r}
m2_pred <- as.data.frame(t(as.matrix(posterior_predict(m2))))
m2_pred_mean <- apply(m2_pred, 1, mean)

model_data %>%
  mutate(post_pred = m2_pred_mean) %>%
  ggplot(aes(rating, post_pred)) +
  geom_jitter(aes(color = post_pred - rating), width = 0.1, height = 0.1) +
  scale_x_continuous(breaks = 0:10) +
  scale_y_continuous(breaks = 0:10) +
  scale_color_gradient2(mid = "grey70") +
  coord_fixed() +
  labs(
    x = "subject rating",
    y = "predicted rating",
    color = "error",
    title = "Posterior predictions by Model 2"
  )
```
